Add initial gentx instructions
defund-labs/testnet pull request #2
Opened 2022-10-25 00:25 UTC by dylanschultzie

Signed-off-by: Dylan Schultz <hello@schultzie.dev>

2022-10-25 00:25 UTC, dylanschultzie commented
@nullmames

2022-10-25 01:35 UTC, nullmames requested changes
see inline comments

2022-10-25 01:39 UTC, dylanschultzie commented on defund-private-2/README.md
> +defundd init $MONIKER_NAME --chain-id defund-testnet-2
@schnetzlerjoe can you confirm please?

2022-10-26 04:38 UTC, nullmames commented on defund-private-2/README.md
> +defundd init $MONIKER_NAME --chain-id defund-private-2
$MONIKER_NAME variable has not yet been set. change to `<moniker>` and add note to replace.

2022-10-26 05:18 UTC, schnetzlerjoe commented on defund-private-2/README.md
> +defundd init $MONIKER_NAME --chain-id defund-testnet-2
defund-private-2 is correct

2022-10-26 05:23 UTC, schnetzlerjoe reviewed
Yeah just need to change the moniker and not sure if we want to change 
```bash
git checkout v0.1.0
```
to
```bash
git checkout v0.1.0-alpha
```
for now until the official release of v0.1.0 prob in a few days or next week?

2022-10-27 06:42 UTC, nullmames commented
Thanks @dylanschultzie

2022-10-27 06:42 UTC, merged